name: vgc_champions
version: "1.0.0"
config-version: 2

profile: vgc_champions

model-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  vgc_champions:
    curated:
      +materialized: table
      +schema: curated
